base:
  random_stage: 42
  log_level: INFO

data_load:
  dataset_csv: 'C:/Users/mxmd/Desktop/dvc learning projects/course-ds-base/data/raw/iris.csv'

featurize:
  features_path: 'C:/Users/mxmd/Desktop/dvc learning projects/course-ds-base/data/processed/featured_iris.csv'
  target_column: target

data_split:
  test_size: 0.2
  trainset_path: 'C:/Users/mxmd/Desktop/dvc learning projects/course-ds-base/data/processed/train_iris.csv'
  testset_path: 'C:/Users/mxmd/Desktop/dvc learning projects/course-ds-base/data/processed/test_iris.csv'

train:

  cv: 3
  estimator_name: logreg
  estimators:
    logreg: # sklearn.linear_model.LogisticRegression
      param_grid: # params of GridSearchCV constructor
        C: [0.001]
        max_iter: [100]
        solver: ['lbfgs']
        multi_class: ['multinomial']
    svm: # sklearn.svm.SVC
      param_grid:
        C: [0.1, 1.0]
        kernel: ['rbf', 'linear']
        gamma: ['scale']
        degree: [3, 5]
  model_path: 'C:/Users/mxmd/Desktop/dvc learning projects/course-ds-base/models/model.joblib'


evaluate:
  reports_dir: 'C:/Users/mxmd/Desktop/dvc learning projects/course-ds-base/reports'
  metrics_file: 'metrics.json'
  confusion_matrix_image: 'confusion_matrix.png'
